[project]
	name = artemis
	company = michisoft
	description = "The ultimate visualization and simulation tool"

[build]
	language = c++17
	optimization = 2
	system = [cmake]
	features = [vs2022, vcpkg]

[build.target:moduleartemis]
	type = shared-library
	source = src/
	include-directories = [src, src/y]
	dependencies = [zlib, vulkan|gl, glew?, glfw?, spirv?, unwind?, dl?, freetype2, armadillo, fftw3?]

[install]
	source = [static/*,plugins/]


